const money = (value) => new Intl.NumberFormat('ru-RU').format(value) + ' ₽';
const header = document.querySelector('.header');
const menu = document.querySelector('.menu-toggle');
const nav = document.querySelector('.nav');
if(nav){
  const mobileBrand=document.createElement('img'); mobileBrand.className='mobile-menu__brand'; mobileBrand.src='assets/auronesta-logo-light.svg'; mobileBrand.alt='AURONESTA DEVELOPMENT';
  const mobileCta=document.createElement('a'); mobileCta.className='button mobile-menu__cta'; mobileCta.href='index.html#feedback'; mobileCta.textContent='Оставить заявку';
  const mobilePhone=document.createElement('a'); mobilePhone.className='mobile-menu__phone'; mobilePhone.href='tel:+74951234567'; mobilePhone.textContent='+7 (495) 123-45-67';
  const mobileSlogan=document.createElement('p'); mobileSlogan.className='mobile-slogan'; mobileSlogan.textContent='Архитектура достойной жизни';
  nav.prepend(mobileBrand); nav.append(mobileCta,mobilePhone,mobileSlogan);
}
const setHeader = () => header?.classList.toggle('is-scrolled', scrollY > 20 || document.body.classList.contains('project-page'));
addEventListener('scroll', setHeader, {passive:true}); setHeader();
let menuScrollY=0;
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('active',open);menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');if(open){menuScrollY=scrollY;document.body.style.top=`-${menuScrollY}px`}document.body.classList.toggle('menu-open',open);if(!open){document.body.style.top='';scrollTo(0,menuScrollY)}});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.classList.remove('active');document.body.classList.remove('menu-open');document.body.style.top='';scrollTo(0,menuScrollY)}));

const grid = document.querySelector('#projects-grid');
if(grid){
  const classFilter=document.querySelector('#class-filter'), district=document.querySelector('#district-filter'), price=document.querySelector('#price-filter'), priceValue=document.querySelector('#price-value'), sort=document.querySelector('#sort'), count=document.querySelector('#result-count'), empty=document.querySelector('#empty');
  let status='Все проекты';
  [...new Set(PROJECTS.map(p=>p.district))].sort().forEach(value=>district.add(new Option(value,value)));
  const card=p=>`<article class="property-card" data-project="${p.id}"><a href="project.html?id=${p.id}" aria-label="Подробнее о проекте ${p.name}"><div class="property-card__image"><img src="${p.image}" alt="Жилой комплекс ${p.name}" loading="lazy"><span class="badge">${p.status}</span></div><div class="property-card__body"><div class="property-card__meta"><span>${p.className}-класс</span><span>Сдача ${p.deadline.split('-').reverse().join('.')}</span></div><h3>${p.name}</h3><p class="property-card__address">${p.district} · ${p.address}</p><div class="property-card__bottom"><div><small>Квартиры от</small><strong>${money(p.price)}</strong></div><span class="detail-link">Подробнее →</span></div></div></a></article>`;
  function render(){let items=PROJECTS.filter(p=>(status==='Все проекты'||p.status===status)&&(!classFilter.value||p.className===classFilter.value)&&(!district.value||p.district===district.value)&&p.price<=+price.value);items.sort((a,b)=>sort.value==='cheap'?a.price-b.price:sort.value==='expensive'?b.price-a.price:sort.value==='deadline'?a.deadline.localeCompare(b.deadline):a.name.localeCompare(b.name,'ru'));grid.innerHTML=items.map(card).join('');count.textContent=`${items.length} ${items.length===1?'проект':'проектов'}`;empty.hidden=items.length>0;priceValue.textContent=`${Math.round(price.value/1000000)} млн ₽`}
  document.querySelectorAll('[data-status]').forEach(btn=>btn.addEventListener('click',()=>{status=btn.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===btn));render()}));[classFilter,district,price,sort].forEach(x=>x.addEventListener('input',render));document.querySelector('#reset').addEventListener('click',()=>{status='Все проекты';classFilter.value='';district.value='';price.value=80000000;sort.value='cheap';document.querySelectorAll('[data-status]').forEach((x,i)=>x.classList.toggle('active',i===0));render()});render();
}
const completedGrid=document.querySelector('#completed-grid');
if(completedGrid&&typeof COMPLETED_PROJECTS!=='undefined'){
  completedGrid.innerHTML=COMPLETED_PROJECTS.map(p=>`<article class="completed-card"><div class="completed-card__image"><img src="${p.image}" alt="ЖК «${p.name}» в Краснодаре" loading="lazy"><span class="badge">Сдан</span></div><div class="completed-card__body"><p class="completed-card__district">Краснодар · ${p.district}</p><h3>ЖК «${p.name}»</h3><p class="completed-card__description">${p.description}</p><div class="completed-card__facts"><span>Год сдачи<b>${p.year}</b></span><span>Квартир<b>${new Intl.NumberFormat('ru-RU').format(p.apartments)}</b></span><span>Статус<b>Сдан</b></span></div><a class="button" href="completed-project.html?id=${p.id}">Подробнее</a></div></article>`).join('');
}
const calc=()=>{const p=+document.querySelector('#calc-price')?.value||0,d=+document.querySelector('#calc-down')?.value||0,y=+document.querySelector('#calc-years')?.value||1,r=.06/12,n=y*12,pay=(p-d)*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);const el=document.querySelector('#monthly');if(el)el.textContent=`≈ ${money(Math.max(0,Math.round(pay/1000)*1000))}`};document.querySelectorAll('#calc-price,#calc-down,#calc-years').forEach(x=>x.addEventListener('input',calc));calc();
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.querySelector('.form-success')?.classList.add('is-visible');form.reset()}));
const detail=document.querySelector('#project-detail');
if(detail){const p=PROJECTS.find(x=>x.id===new URLSearchParams(location.search).get('id'));if(!p){detail.innerHTML='<section class="project-hero container"><h1>Проект не найден</h1><a href="index.html#projects">Вернуться в каталог</a></section>'}else{document.title=`${p.name} — AURONESTA DEVELOPMENT`;const gallery=[p.image,PROJECTS[(PROJECTS.indexOf(p)+1)%15].image,PROJECTS[(PROJECTS.indexOf(p)+2)%15].image];detail.innerHTML=`<section class="project-hero"><div class="container"><div class="project-hero__head"><div><p class="eyebrow">${p.status} · ${p.className}-класс</p><h1>${p.name}</h1><p>${p.address}</p></div><div class="project-hero__price">от ${money(p.price)}</div></div><div class="gallery">${gallery.map((src,i)=>`<img src="${src}" alt="${p.name}, фото ${i+1}">`).join('')}</div></div></section><section class="project-content"><div class="container project-layout"><div><h2>О проекте</h2><p class="lead">${p.description}</p><h2>Преимущества</h2><ul class="advantages-list">${p.advantages.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><div class="info-table"><div><span>Адрес</span><b>${p.address}</b></div><div><span>Класс жилья</span><b>${p.className}</b></div><div><span>Срок сдачи</span><b>${p.deadline.split('-').reverse().join('.')}</b></div><div><span>Статус</span><b>${p.status}</b></div></div><h2>Варианты квартир и цены</h2><ul class="apartments">${p.apartments.map(x=>`<li>${x}</li>`).join('')}</ul><h2>Инфраструктура</h2><p class="lead">${p.infra}</p></div><aside class="viewing"><p class="eyebrow">Персональная встреча</p><h3>Записаться на просмотр</h3><p>Покажем проект и подберём планировку.</p><form><input required placeholder="Ваше имя"><input required type="tel" placeholder="Телефон"><button class="button">Оставить заявку</button><a class="button button--ghost" href="tel:+74951234567">Позвонить</a><p class="form-success">Спасибо! Команда AURONESTA DEVELOPMENT свяжется с вами.</p></form></aside></div></section>`}}
const completedDetail=document.querySelector('#completed-detail');
if(completedDetail&&typeof COMPLETED_PROJECTS!=='undefined'){
  const p=COMPLETED_PROJECTS.find(x=>x.id===new URLSearchParams(location.search).get('id'));
  if(!p){completedDetail.innerHTML='<section class="completed-detail container"><h1>Проект не найден</h1><a class="button" href="index.html#completed-projects">Вернуться к проектам</a></section>'}else{document.title=`ЖК «${p.name}» — реализованный проект AURONESTA DEVELOPMENT`;completedDetail.innerHTML=`<section class="completed-detail"><div class="container completed-detail__hero"><img src="${p.image}" alt="ЖК «${p.name}» в Краснодаре"><div><p class="eyebrow">Реализованный проект · Сдан</p><h1>ЖК «${p.name}»</h1><p class="lead">${p.description}</p><div class="completed-detail__facts"><div><small>Год сдачи</small><b>${p.year}</b></div><div><small>Количество квартир</small><b>${new Intl.NumberFormat('ru-RU').format(p.apartments)}</b></div><div><small>Район</small><b>${p.district}</b></div><div><small>Город</small><b>Краснодар</b></div></div><p class="completed-detail__note">Дом сдан и заселён. Квартиры в этом комплексе не представлены в каталоге актуальных предложений.</p><a class="text-link" href="index.html#completed-projects">← Все реализованные проекты</a></div></div></section>`}
}
// Keep the SVG identity visible in the footer on standalone portfolio pages.
if(!document.querySelector('footer')){
  const brandedFooter=document.createElement('footer');
  brandedFooter.className='brand-footer';
  brandedFooter.innerHTML='<div class="container brand-footer__inner"><img src="assets/auronesta-logo-light.svg" alt="AURONESTA DEVELOPMENT"><p>Архитектура достойной жизни</p></div>';
  document.body.append(brandedFooter);
}
const existingFooter=document.querySelector('footer:not(.brand-footer)');
if(existingFooter&&!existingFooter.querySelector('img[src*="auronesta-logo"]')){
  const footerIdentity=document.createElement('a'); footerIdentity.className='footer-identity'; footerIdentity.href='index.html'; footerIdentity.setAttribute('aria-label','AURONESTA DEVELOPMENT — на главную'); footerIdentity.innerHTML='<img src="assets/auronesta-logo-light.svg" alt="AURONESTA DEVELOPMENT">'; existingFooter.prepend(footerIdentity);
}
